---
title: "Signature analysis"
subtitle: "Adult human endothelial CNS-peripheral signature, MHC class II signature, Fetal human endothelial CNS-peripheral signature, Adult mouse endothelial CNS-peripheral signature,BBB dysfunction module signature and BBB signature analysis" 
author: "Moheb Ghobrial"
output: html_notebook
---

```{r}
#load libraries 
library(Seurat)

# Load the seurat object of the overall merge of all brain sorted CD31+/CD45- endothelial cells 
RPCA <- readRDS(file = "Overall merge of all brain sorted endothelial cells_seurat object.rds")
# set default assay to RNA
DefaultAssay(RPCA) <- "RNA"

```

```{r}
#Adult human endothelial CNS and peripheral signature analysis
#related to Figure 4 a-h
#related to Supplementary Figure 14 a-c, Supplementary Figure 15a

#Load adult human CNS EC signature genes
AdultCNSsignature <- c("PLP1","CLDN5","GPM6B","TF","BSG","S100B","MBP","GPR85","SLC7A5","PTGDS","SLC2A1","ITM2A","MT3","CNP","SLC38A5","ATP1A2","SPOCK2","SLCO2B1","C1orf61",
"APLP1","TUBB4A","QDPR","SCD","MFSD2A","ABCG2","SLC1A3","RN7SK","PPP1R14A","SPOCK3","CRYAB","CKB","TMEM144","PLLP","SRARP","SLC39A10","MAG","ERMN","CLDN11","APOLD1","SCG3",
"SCD5","SOX2-OT","TUBA1A","CA4","GPRC5B","CNDP1","CBR1","GPCPD1","LINC00844","CD320")

# Generate mean of expression of the signature genes
AdultCNSsignature_mean <- Matrix::colMeans(RPCA[AdultCNSsignature, ])

# Add matrix to data
RPCA <- AddMetaData(RPCA, metadata = AdultCNSsignature_mean,  col.name = "AdultCNSsignature_mean")


#to plot the expression of the individual genes of the signature - Figure 4d
DotPlot(RPCA, features = AdultCNSsignature, cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) + RotatedAxis() 

#plot dotplots for expression of the signature in fetal brain vs adult/control brain vs pathological brain ECs - Figure 4e (first column)
Idents(RPCA) <- "PATH2"
DotPlot(RPCA, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 


#plot dotplots for expression of the signature by pathology - Figure 4f (first column)
Idents(RPCA) <- "PATH"
DotPlot(RPCA, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 



#plot dotplots for expression of the signature according to the AV specification - Figure 4g
Idents(RPCA) <- "ECclusters"
levels(RPCA) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")
DotPlot(RPCA, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 


Idents(RPCA) <- "PATH"

#for fetal brain endothelial cells
FETALCNS <- subset(RPCA, idents = c("FETALCNS"))
Idents(FETALCNS) <- "ECclusters"
levels(FETALCNS) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(FETALCNS, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)  

#for adult/control brain endothelial cells
TL <- subset(RPCA, idents = c("TL"))
Idents(TL) <- "ECclusters"
levels(TL) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(TL, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)  

#for brain vascular malformation (arteriovenous malformation) endothelial cells (AVM/Brain vasc. MAL)
AVM <- subset(RPCA, idents = c("AVM"))
Idents(AVM) <- "ECclusters"
levels(AVM) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(AVM, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#for lower-grade glioma (LGG) endothelial cells
LGG <- subset(RPCA, idents = c("LGG"))
Idents(LGG) <- "ECclusters"
levels(LGG) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(LGG, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)

#for high-grade glioma/glioblastoma (GBM) endothelial cells
GBM <- subset(RPCA, idents = c("GBM"))
Idents(GBM) <- "ECclusters"
levels(GBM) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(GBM, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)

#for metastasis (MET) endothelial cells
MET <- subset(RPCA, idents = c("MET"))
Idents(MET) <- "ECclusters"
levels(MET) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(MET, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)

#for meningioma (MEN) endothelial cells
MEN <- subset(RPCA, idents = c("MEN"))
Idents(MEN) <- "ECclusters"
levels(MEN) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(MEN, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)


#for all pathological brain endothelial cells (PATH)
Idents(RPCA) <- "PATH2"
PATH <- subset(RPCA, idents = c("Pathology"))
Idents(PATH) <- "ECclusters"
levels(PATH) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(PATH, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)


#for all brain tumor endothelial cells (Brain tumors)
Idents(RPCA) <- "PATH3"
TUM <- subset(RPCA, idents = c("TUM"))
Idents(TUM) <- "ECclusters"
levels(TUM) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(TUM, features = "AdultCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)


#violn plot for expression of some CNS specific genes - Figure 4h
Idents(RPCA) <- "PATH2"
levels(RPCA) <- c("Fetal","Control","Pathology")
VlnPlot(RPCA, features = c("SPOCK3"), log = TRUE,pt.size = 0, cols = c('Fetal' = '#A0E4A8', 'Control' = 'turquoise3', 'Pathology' = '#f8766d'))
VlnPlot(RPCA, features = c("GPCPD1"), log = TRUE,pt.size = 0, cols = c('Fetal' = '#A0E4A8', 'Control' = 'turquoise3', 'Pathology' = '#f8766d'))
VlnPlot(RPCA, features = c("BSG"), log = TRUE,pt.size = 0, cols = c('Fetal' = '#A0E4A8', 'Control' = 'turquoise3', 'Pathology' = '#f8766d'))
VlnPlot(RPCA, features = c("PPP1R14A"), log = TRUE,pt.size = 0, cols = c('Fetal' = '#A0E4A8', 'Control' = 'turquoise3', 'Pathology' = '#f8766d'))
VlnPlot(RPCA, features = c("CD320"), log = TRUE,pt.size = 0, cols = c('Fetal' = '#A0E4A8', 'Control' = 'turquoise3', 'Pathology' = '#f8766d'))
VlnPlot(RPCA, features = c("SLC38A5"), log = TRUE,pt.size = 0, cols = c('Fetal' = '#A0E4A8', 'Control' = 'turquoise3', 'Pathology' = '#f8766d'))
VlnPlot(RPCA, features = c("ADGRA2"), log = TRUE,pt.size = 0, cols = c('Fetal' = '#A0E4A8', 'Control' = 'turquoise3', 'Pathology' = '#f8766d'))
VlnPlot(RPCA, features = c("SLC2A1"), log = TRUE,pt.size = 0, cols = c('Fetal' = '#A0E4A8', 'Control' = 'turquoise3', 'Pathology' = '#f8766d'))
VlnPlot(RPCA, features = c("CLDN5"), log = TRUE,pt.size = 0, cols = c('Fetal' = '#A0E4A8', 'Control' = 'turquoise3', 'Pathology' = '#f8766d'))
VlnPlot(RPCA, features = c("TJP1"), log = TRUE,pt.size = 0, cols = c('Fetal' = '#A0E4A8', 'Control' = 'turquoise3', 'Pathology' = '#f8766d'))
VlnPlot(RPCA, features = c("OCLN"), log = TRUE,pt.size = 0, cols = c('Fetal' = '#A0E4A8', 'Control' = 'turquoise3', 'Pathology' = '#f8766d'))


#Load adult human peripheral EC signature genes
AdultPeriphsignature <-
c("LDHA","NCOA7","TM4SF1","NNMT","CXCL3","FABP5","SLPI","GAS5","IGFBP4","DDX21","POSTN","IL33","MT-RNR2","CD36","THBS1","PDLIM1","HIF1A","RND1","CD93","SLCO2A1",
"ICAM1","CRHBP","TFPI","CALCRL","COL15A1","SOCS3","PNP","SOD2","ADAMTS9","HLA-DRB5","CCL2","CXCL2","FABP4","PLVAP","PLPP3","SERPINE1","ACKR1","DNASE1L3","FCN3","THBD",
"IGKC","STC1","IGFBP5","HMOX1","EMP1","AQP1","CSF3","IL6","CXCL8","SELE")

# Generate mean of expression of the signature genes
AdultPeriphsignature_mean <- Matrix::colMeans(RPCA[AdultPeriphsignature, ])

# Add matrix to data
RPCA <- AddMetaData(RPCA, metadata = AdultPeriphsignature_mean,  col.name = "AdultPeriphsignature_mean")

#to plot the expression of the individual genes of the signature - Supplementary Figure 14g
DotPlot(RPCA, features = AdultPeriphsignature, cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) + RotatedAxis() 

#plot dotplots for expression of the signature according to the AV specification - Supplementary Figure 14h
# for all brain endothelial cells
Idents(RPCA) <- "ECclusters"
levels(RPCA) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")
DotPlot(RPCA, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)


#for fetal brain endothelial cells
FETALCNS <- subset(RPCA, idents = c("FETALCNS"))
Idents(FETALCNS) <- "ECclusters"
levels(FETALCNS) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(FETALCNS, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)  

#for adult/control brain endothelial cells
TL <- subset(RPCA, idents = c("TL"))
Idents(TL) <- "ECclusters"
levels(TL) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(TL, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)  

#for brain vascular malformation (arteriovenous malformation) endothelial cells (AVM/Brain vasc. MAL)
AVM <- subset(RPCA, idents = c("AVM"))
Idents(AVM) <- "ECclusters"
levels(AVM) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(AVM, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#for lower-grade glioma (LGG) endothelial cells
LGG <- subset(RPCA, idents = c("LGG"))
Idents(LGG) <- "ECclusters"
levels(LGG) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(LGG, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)

#for high-grade glioma/glioblastoma (GBM) endothelial cells
GBM <- subset(RPCA, idents = c("GBM"))
Idents(GBM) <- "ECclusters"
levels(GBM) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(GBM, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)

#for metastasis (MET) endothelial cells
MET <- subset(RPCA, idents = c("MET"))
Idents(MET) <- "ECclusters"
levels(MET) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(MET, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)

#for meningioma (MEN) endothelial cells
MEN <- subset(RPCA, idents = c("MEN"))
Idents(MEN) <- "ECclusters"
levels(MEN) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(MEN, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)


#for all pathological brain endothelial cells (PATH)
Idents(RPCA) <- "PATH2"
PATH <- subset(RPCA, idents = c("Pathology"))
Idents(PATH) <- "ECclusters"
levels(PATH) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(PATH, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)


#for all brain tumor endothelial cells (Brain tumors)
Idents(RPCA) <- "PATH3"
TUM <- subset(RPCA, idents = c("TUM"))
Idents(TUM) <- "ECclusters"
levels(TUM) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(TUM, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100)


#plot dotplots for expression of the signature by pathology - Figure 4f (second column)
Idents(RPCA) <- "PATH"
DotPlot(RPCA, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 


#plot dotplots for expression of the signature in fetal brain vs adult/control brain vs pathological brain ECs - Figure 4e (second column)
Idents(RPCA) <- "PATH2"
DotPlot(RPCA, features = "AdultPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#to plot the expression of the individual genes of the signature - Supplementary figure 11g
DotPlot(RPCA, features = AdultPeriphsignature, cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) + RotatedAxis() 


#to plot a UMAP with the blend of the Adult CNS and peripheral signature in fetal brain vs adult/control brain vs pathological brain ECs - Figure 4a-c
FeaturePlot(RPCA, features = c("AdultCNSsignature_mean","AdultPeriphsignature_mean"),split.by = "PATH2", blend = TRUE, reduction = 'UMAP',  label = FALSE, repel = TRUE, label.size = 4,pt.size = 0.1,cols = c("#92B2B1", "#C09902"), min.cutoff = "q05", max.cutoff = "q90",raster=FALSE,blend.threshold = 0.5)


#to plot a UMAP with the blend of the Adult CNS and peripheral signature in individual entity ECs - Supplementary figure 11r
FeaturePlot(RPCA, features = c("AdultCNSsignature_mean","AdultPeriphsignature_mean"),split.by = "PATH", blend = TRUE, reduction = 'UMAP',  label = FALSE, repel = TRUE, label.size = 4,pt.size = 0.1,cols = c("#92B2B1", "#C09902"), min.cutoff = "q05", max.cutoff = "q90",raster=FALSE,blend.threshold = 0.5)

#End
```

```{r}
#MHC class II signature analysis
#related to Figure 5 a-g

#Load MHC class II signature genes
MHCCLASSII <- c("CD74","HLA-DRB5","HLA-DRB1","HLA-DQB2","HLA-DQB1","HLA-DPB1","HLA-DOB","HLA-DMB","HLA-DRA","HLA-DQA2","HLA-DQA1","HLA-DPA1","HLA-DOA","HLA-DMA")  

# Generate mean of expression of the signature genes
MHCCLASSII_mean <- Matrix::colMeans(RPCA[MHCCLASSII, ])

# Add matrix to data
RPCA <- AddMetaData(RPCA, metadata = MHCCLASSII_mean, col.name = "MHCCLASSII_mean")

#to plot the expression of the individual genes of the signature - Figure 5d
DotPlot(RPCA, features = MHCCLASSII, cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10) + RotatedAxis() 

#plot dotplots for expression of the signature in fetal brain vs adult/control brain vs pathological brain ECs - Figure 5e (first column)
Idents(RPCA) <- "PATH2"
DotPlot(RPCA, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10) 

#plot dotplots for expression of the signature by pathology - Figure 5f
Idents(RPCA) <- "PATH"
DotPlot(RPCA, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 



#plot dotplots for expression of the signature according to the AV specification - Figure 5g

#for all brain endothelial cells (ALL cells)
Idents(RPCA) <- "ECclusters"
levels(RPCA) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(RPCA, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10) 


Idents(RPCA) <- "PATH"

#for fetal brain endothelial cells
FETALCNS <- subset(RPCA, idents = c("FETALCNS"))
Idents(FETALCNS) <- "ECclusters"
levels(FETALCNS) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(FETALCNS, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10) 

#for adult/control brain endothelial cells
TL <- subset(RPCA, idents = c("TL"))
Idents(TL) <- "ECclusters"
levels(TL) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(TL, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10) 

#for brain vascular malformation (arteriovenous malformation) endothelial cells (AVM/Brain vasc. MAL)
AVM <- subset(RPCA, idents = c("AVM"))
Idents(AVM) <- "ECclusters"
levels(AVM) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(AVM, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10) 

#for lower-grade glioma (LGG) endothelial cells
LGG <- subset(RPCA, idents = c("LGG"))
Idents(LGG) <- "ECclusters"
levels(LGG) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(LGG, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10) 

#for high-grade glioma/glioblastoma (GBM) endothelial cells
GBM <- subset(RPCA, idents = c("GBM"))
Idents(GBM) <- "ECclusters"
levels(GBM) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(GBM, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10) 

#for metastasis (MET) endothelial cells
MET <- subset(RPCA, idents = c("MET"))
Idents(MET) <- "ECclusters"
levels(MET) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(MET, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10)

#for meningioma (MEN) endothelial cells
MEN <- subset(RPCA, idents = c("MEN"))
Idents(MEN) <- "ECclusters"
levels(MEN) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(MEN, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10)


#for all pathological brain endothelial cells (PATH)
Idents(RPCA) <- "PATH2"
PATH <- subset(RPCA, idents = c("Pathology"))
Idents(PATH) <- "ECclusters"
levels(PATH) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(PATH, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10)


#for all brain tumor endothelial cells (Brain tumors)
Idents(RPCA) <- "PATH3"
TUM <- subset(RPCA, idents = c("TUM"))
Idents(TUM) <- "ECclusters"
levels(TUM) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")

DotPlot(TUM, features = "MHCCLASSII_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100, col.min = 0, col.max = 10)


#to plot a UMAP with the blend of the MHC class II and Adult CNS signature in fetal brain vs adult/control brain vs pathological brain ECs - Figure 5a-c
FeaturePlot(RPCA, features = c("MHCCLASSII_mean","AdultCNSsignature_mean"),split.by = "PATH2", blend = TRUE, reduction = 'UMAP',  label = FALSE, repel = TRUE, label.size = 4,pt.size = 0.1,cols = c("#8684C3","#92B2B1"), min.cutoff = "q05", max.cutoff = "q90",raster=FALSE,blend.threshold = 0.5)

#to plot a UMAP with the blend of the MHC class II and Adult CNS signature in individual entity ECs
FeaturePlot(RPCA, features = c("MHCCLASSII_mean","AdultCNSsignature_mean"),split.by = "PATH", blend = TRUE, reduction = 'UMAP',  label = FALSE, repel = TRUE, label.size = 4,pt.size = 0.1,cols = c("#8684C3","#92B2B1"), min.cutoff = "q05", max.cutoff = "q90",raster=FALSE,blend.threshold = 0.5)

#End
```


```{r}
#Fetal human endothelial CNS and peripheral signature analysis
#related to Supplementary Figure 14 d-f,l-q, Supplementary Figure 15b

#Load fetal EC CNS signature genes
FETALCNSsig <-c("SLC7A5","SLC38A5","TTN","TFRC","MT2A","MFSD2A","SLC7A1","SLC2A1","MT1E","ITM2A","APCDD1","NPIPB5","CLDN5","ABCG2","SLC39A10","SLC16A1","GPCPD1","ABCB1","SLCO1A2","PDXK","IFI27","SLC3A2","SLCO2B1","BSG","ABLIM1","COBLL1","CDH2","SRARP","CSRP2","LRP8","CCDC141","SLC7A8","TSC22D1","RELL1","MT1X","LEF1","CGNL1","FOXQ1","SLC7A11","HOPX","SMG1","CPD","TSPAN5","CD82","CCDC186","ZIC2","CD320","SLC30A1","DPEP1","MT-RNR1")

# Generate mean of expression of the markers
FETALCNSsig_mean <- Matrix::colMeans(RPCA[FETALCNSsig, ])

# Add matrix to data
RPCA <- AddMetaData(RPCA, metadata = FETALCNSsig_mean,  col.name = "FETALCNSsig_mean")

#to plot the expression of the individual genes of the signature - Supplementary Figure 14o
DotPlot(RPCA, features = FETALCNSsig, cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) + RotatedAxis() 

#plot dotplots for expression of the signature according to the AV specification 
Idents(RPCA) <- "ECclusters"
levels(RPCA) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")
DotPlot(RPCA, features = "FETALCNSsig_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#plot dotplots for expression of the signature by pathology
Idents(RPCA) <- "PATH"
DotPlot(RPCA, features = "FETALCNSsig_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#plot dotplots for expression of the signature in fetal brain vs adult/control brain vs pathological brain ECs
Idents(RPCA) <- "PATH2"
DotPlot(RPCA, features = "FETALCNSsig_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#to plot the expression of the individual genes of the signature 
DotPlot(RPCA, features = FETALCNSsig, cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) + RotatedAxis()


#Load fetal EC peripehry signature genes
FETALPERIPHsig <- c("IGFBP5","FABP5","FABP4","LGALS1","COL15A1","IGF2","PLVAP","ANXA2","CD36","MEIS2","PLPP3","TCIM","TNNT3","PCDH17","GYPC","CRHBP","IGFBP3","PRCP","C11orf96","CAV1","AQP1","CALCRL","F8","PIEZO2","HSPG2","EDNRB","HECW2","MAF","TXNIP","LDB2","ID2","LYVE1","GASK1B","IL32","C1orf21","SPRY1","FAM167B","EMCN","COL4A1","TFPI","NEURL1B","HSPB1","S100A11","NAV3","FBN1","MXRA5","S100A10","NR2F2","STMN1","RBP7")

# Generate mean of expression of the markers
FETALPERIPHsig_mean <- Matrix::colMeans(RPCA[FETALPERIPHsig, ])

# Add matrix to data
RPCA <- AddMetaData(RPCA, metadata = FETALPERIPHsig_mean,  col.name = "FETALPERIPHsig_mean")

#plot dotplots for expression of the signature according to the AV specification 
Idents(RPCA) <- "ECclusters"
levels(RPCA) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")
DotPlot(RPCA, features = "FETALPERIPHsig_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#plot dotplots for expression of the signature by pathology
Idents(RPCA) <- "PATH"
DotPlot(RPCA, features = "FETALPERIPHsig_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 


#plot dotplots for expression of the signature in fetal brain vs adult/control brain vs pathological brain ECs
Idents(RPCA) <- "PATH2"
DotPlot(RPCA, features = "FETALPERIPHsig_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#to plot the expression of the individual genes of the signature 
DotPlot(RPCA, features = FETALPERIPHsig, cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) + RotatedAxis() 


#to plot a UMAP with the blend of the Adult CNS and peripheral signature in fetal brain vs adult/control brain vs pathological brain ECs
FeaturePlot(RPCA, features = c("FETALCNSsig_mean","FETALPERIPHsig_mean"),split.by = "PATH2", blend = TRUE, reduction = 'UMAP',  label = FALSE, repel = TRUE, label.size = 4,pt.size = 0.1,cols = c("#92B2B1", "#C09902"), min.cutoff = "q05", max.cutoff = "q90",raster=FALSE,blend.threshold = 0.5)


#to plot a UMAP with the blend of the Adult CNS and peripheral signature in individual entity ECs
FeaturePlot(RPCA, features = c("FETALCNSsig_mean","FETALPERIPHsig_mean"),split.by = "PATH", blend = TRUE, reduction = 'UMAP',  label = FALSE, repel = TRUE, label.size = 4,pt.size = 0.1,cols = c("#92B2B1", "#C09902"), min.cutoff = "q05", max.cutoff = "q90",raster=FALSE,blend.threshold = 0.5)

#End
```


```{r}
#Adult mouse endothelial CNS and peripheral signature analysis
#related to Supplementary Figure 15 c

#Load adult mouse brain EC signature genes (from Munji et al Nature Neuroscience 2019)
MunjiCNSsignature <- c("SPOCK2","SLCO1A4","SLC2A1","SLCO1C1","SLC22A8","ABCB1A", "ITM2A","LEF1","SLC7A5","ITIH5","BSG","MFSD2A","LRP8","CXCL12","PGLYRP1","ZIC3","SLC38A3", "ABHD2","TFRC","APCDD1","SLC6A6","PROM1","APOD","CCDC141","SLC19A3","FLT1","PTN","FOXF2","SLC39A10","SPARCL1","ZIC2","SLC1A1","ATP10A","A930038C07RIK","TNFRSF19","FOXQ1","FOSB","STRA6","SLC7A1","9430020K01RIK","VWA1","PLTP","EFR3B","GPCPD1","SGPP2","MFSD14A","IGF1R",
"OCLN","SLC16A4")

# Generate mean of expression of the markers
MunjiCNSsignature_mean <- Matrix::colMeans(RPCA[MunjiCNSsignature, ])

# Add matrix to data
RPCA <- AddMetaData(RPCA, metadata = MunjiCNSsignature_mean,  col.name = "MunjiCNSsignature_mean")

#plot dotplots for expression of the signature according to the AV specification 
Idents(RPCA) <- "ECclusters"
levels(RPCA) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")
DotPlot(RPCA, features = "MunjiCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#plot dotplots for expression of the signature by pathology
Idents(RPCA) <- "PATH"
DotPlot(RPCA, features = "MunjiCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 


#plot dotplots for expression of the signature in fetal brain vs adult/control brain vs pathological brain ECs
Idents(RPCA) <- "PATH2"
DotPlot(RPCA, features = "MunjiCNSsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#to plot the expression of the individual genes of the signature 
DotPlot(RPCA, features = MunjiCNSsignature, cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) + RotatedAxis() 



#Load adult mouse periphery EC signature genes (derived from Munji et al., Nature Neuroscience 2019)
MunjiPeriphsignature <- c("AQP1","IGFBP5","CD36","FABP4","GPIHBP1","MRC1","NPR3","CYP4B1",
"MEIS2","EDNRB","SLC43A3","LYVE1","TSPAN7","BTNL9","MMRN1","SELP","HPGD", "F8",
"PLVAP","CA8","SLCO2A1","LYZ","F2R","SERPINA3","PLPP3","NEURL3","CXCL9","IGFBP4","ESM1",
"PTGS1","CYTL1","CD300LG","GPR182","HECW2","CCDC80","RELN","CD74"," FAM174B",
"MLXIP","GIMAP4","ITGA9","LBP","PLPP1","FAM124A","BGN","LDB2","FSTL1","BACE2", "HLA-DQA1", "HLA-DQA2")


# Generate mean of expression of the markers
MunjiPeriphsignature_mean <- Matrix::colMeans(RPCA[MunjiPeriphsignature, ])

# Add matrix to data
RPCA <- AddMetaData(RPCA, metadata = MunjiPeriphsignature_mean,  col.name = "MunjiPeriphsignature_mean")

#plot dotplots for expression of the signature according to the AV specification 
Idents(RPCA) <- "ECclusters"
levels(RPCA) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")
DotPlot(RPCA, features = "MunjiPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#plot dotplots for expression of the signature by pathology
Idents(RPCA) <- "PATH"
DotPlot(RPCA, features = "MunjiPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 


#plot dotplots for expression of the signature in fetal brain vs adult/control brain vs pathological brain ECs
Idents(RPCA) <- "PATH2"
DotPlot(RPCA, features = "MunjiPeriphsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#to plot the expression of the individual genes of the signature 
DotPlot(RPCA, features = AdultPeriphsignature, cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) + RotatedAxis() 


#to plot a UMAP with the blend of the Adult CNS and peripheral signature in fetal brain vs adult/control brain vs pathological brain ECs
FeaturePlot(RPCA, features = c("MunjiCNSsignature_mean","MunjiPeriphsignature_mean"),split.by = "PATH2", blend = TRUE, reduction = 'UMAP',  label = FALSE, repel = TRUE, label.size = 4,pt.size = 0.1,cols = c("#92B2B1", "#C09902"), min.cutoff = "q05", max.cutoff = "q90",raster=FALSE,blend.threshold = 0.5)


#to plot a UMAP with the blend of the Adult CNS and peripheral signature in individual entity ECs
FeaturePlot(RPCA, features = c("MunjiCNSsignature_mean","MunjiPeriphsignature_mean"),split.by = "PATH", blend = TRUE, reduction = 'UMAP',  label = FALSE, repel = TRUE, label.size = 4,pt.size = 0.1,cols = c("#92B2B1", "#C09902"), min.cutoff = "q05", max.cutoff = "q90",raster=FALSE,blend.threshold = 0.5)

#End
```


```{r}
# BBB dysfunction module signature analysis
#related to Supplementary Figure 16 a-n

#Load mouse brain BBB dysfunction module signature (from Munji et al Nature Neuroscience 2019)
BBBDYSFUNCTIONALMODULE <- c("ACOT7", "ADAM12", "ADAMTS4","ADAMTS8","AEBP1","ALDH18A1", "ALDH1A2","ANLN","ANXA1",
"APLN","APLNR","APRT","ASPM","ATP8B1","B3GNT3","BICC1","BMP1", "BUB1B","CIP2A","CASP4","CCL2","CCNA2","CCNB2","CD14",
"CD44","CDK1","CENPE","CENPF","CH25H","CHST1","CKAP2","CKS1B","CKS1B","CMTM3","COL12A1","COL1A1","COL1A2","COL3A1",
"COL5A1","COL5A2","CXCL10","CYP1B1","ACKR1","DCN","DKK3","DPYSL3","EMILIN1","FBLN1","FBN1","FKBP10","FLNC","FRRS1","FSCN1")


# Generate mean of expression of the markers
BBBDYSFUNCTIONALMODULE_mean <- Matrix::colMeans(RPCA[BBBDYSFUNCTIONALMODULE, ])

# Add matrix to data
RPCA <- AddMetaData(RPCA, metadata = BBBDYSFUNCTIONALMODULE_mean,  col.name = "BBBDYSFUNCTIONALMODULE_mean")

#to plot a UMAP with the blend of the Adult CNS and BBB dysfunction module signature in individual entity ECs
FeaturePlot(RPCA, features = c("AdultCNSsignature_mean","BBBDYSFUNCTIONALMODULECOREGENES_mean"),split.by = "PATH", blend = TRUE, reduction = 'UMAP',  label = FALSE, repel = TRUE, label.size = 4,pt.size = 0.1,cols = c("#92B2B1", "#594402"), min.cutoff = "q05", max.cutoff = "q90",raster=FALSE,blend.threshold = 0.5)


#to plot a UMAP with the blend of the Adult peripheral and BBB dysfunction module signature in individual entity ECs
FeaturePlot(RPCA, features = c("AdultPeriphsignature_mean","BBBDYSFUNCTIONALMODULECOREGENES_mean"),split.by = "PATH", blend = TRUE, reduction = 'UMAP',  label = FALSE, repel = TRUE, label.size = 4,pt.size = 0.1,cols = c("#C09902", "#594402"), min.cutoff = "q05", max.cutoff = "q90",raster=FALSE,blend.threshold = 0.5)

```

```{r}
#Load blood brain barrier signature genes (fromZhao et al., Cell 2015)
BBB <- c("ABCB1","ABCA2","ABCG2","ABCC1","ABCC2","ABCC3","ABCC4","ABCC5","SLC2A1","SLC5A1","SLC2A13", "SLC5A3","SLC7A1","SLC7A3","SLC7A5","SLC7A6","SLC38A1","SLC38A2","SLC38A3","SLC38A5","SLC1A4","SLC1A5","SLC1A3","SLC1A2","SLC1A1","SLC6A9","SLC6A6","SLC16A1","SLC16A7","SLC16A2","SLC27A1","SLC27A4","SLC28A2","SLC29A1","SLC29A2","SLC22A8","SLCO1A4","SLCO2B1","SLCO1C1","SLC22A1","SLC22A2","SLC22A3","SLC22A5","SLC29A4","SLC44A1","SLC5A6","AVPR1A","TFRC","TFR2","LEPR","INSR","LRP1","LRP2","AGER","MFSD2A","OCLN","CLDN1","CLDN3","CLDN5","CLDN12","TJP1","TJP2","TJP3","CDH5","PECAM1","F11R","JAM2","JAM3","ESAM","GJB6","GJA1","DMD")


# Generate mean of expression of the markers
BBBsignature_mean <- Matrix::colMeans(RPCA[BBB, ])

# Add matrix to data
RPCA <- AddMetaData(RPCA, metadata = BBBsignature_mean,  col.name = "BBBsignature_mean")


#plot dotplots for expression of the signature according to the AV specification 
Idents(RPCA) <- "ECclusters"
levels(RPCA) <- c("Proliferating Stem-to-EC","Stem-to-EC", "Proliferating cell", "Proliferating EndoMT","EndoMT","Mitochondrial", "Large vein", "Vein", "Venule", "Capillary","Angiogenic capillary", "Arteriole", "Artery","Large artery")
DotPlot(RPCA, features = "BBBsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#plot dotplots for expression of the signature by pathology
Idents(RPCA) <- "PATH"
DotPlot(RPCA, features = "BBBsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 


#plot dotplots for expression of the signature in fetal brain vs adult/control brain vs pathological brain ECs
Idents(RPCA) <- "PATH2"
DotPlot(RPCA, features = "BBBsignature_mean", cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) 

#to plot the expression of the individual genes of the signature 
DotPlot(RPCA, features = BBB, cols = c("blue", "red"), dot.scale = 6, scale = TRUE, scale.by = "size", dot.min = 0, scale.min = 0, scale.max = 100) + RotatedAxis() 
```

